// This component is used to have simple acces to images from the image library
// React Native is not allow dynamic import, so we need to use require for every single image
//
// NB: Please, add the new images in alphabetical order

export const avocado = require('@/assets/library/avocado.png')
export const blender = require('@/assets/library/blender.png')
export const bread = require('@/assets/library/bread.png')
export const butter = require('@/assets/library/butter.png')
export const caffeine = require('@/assets/library/caffeine.png')
export const cheese = require('@/assets/library/cheese.png')
export const corn = require('@/assets/library/corn.png')
export const eggplant = require('@/assets/library/eggplant.png')
export const eggs = require('@/assets/library/eggs.png')
export const fish = require('@/assets/library/fish.png')
export const fructose = require('@/assets/library/fructose.png')
export const gluten = require('@/assets/library/gluten.png')
export const meat = require('@/assets/library/meat.png')
export const melon = require('@/assets/library/melon.png')
export const milk = require('@/assets/library/milk.png')
export const oil = require('@/assets/library/oil.png')
export const onion = require('@/assets/library/onion.png')
export const parsley = require('@/assets/library/parsley.png')
export const pasta = require('@/assets/library/pasta.png')
export const peppers = require('@/assets/library/peppers.png')
export const recipe = require('@/assets/library/recipe.png')
export const sucrose = require('@/assets/library/sucrose.png')
export const vegetarian = require('@/assets/library/vegetarian.png')

export const icons = {
    alcoholic_beverage: require('@/assets/library/ingredient-categories/alcoholic_beverage.webp'),
    alfalfa_seeds: require('@/assets/library/ingredient-categories/alfalfa_seeds.webp'),
    animal_fat: require('@/assets/library/ingredient-categories/animal_fat.webp'),
    apples: require('@/assets/library/ingredient-categories/apples.webp'),
    apricots: require('@/assets/library/ingredient-categories/apricots.webp'),
    artichokes: require('@/assets/library/ingredient-categories/artichokes.webp'),
    arugula: require('@/assets/library/ingredient-categories/arugula.webp'),
    asparagus: require('@/assets/library/ingredient-categories/asparagus.webp'),
    avocados: require('@/assets/library/ingredient-categories/avocados.webp'),
    bacon: require('@/assets/library/ingredient-categories/bacon.webp'),
    bagels: require('@/assets/library/ingredient-categories/bagels.webp'),
    baking_chocolate: require('@/assets/library/ingredient-categories/baking_chocolate.webp'),
    "balsam-pear": require('@/assets/library/ingredient-categories/balsam-pear.webp'),
    bananas: require('@/assets/library/ingredient-categories/bananas.webp'),
    barley: require('@/assets/library/ingredient-categories/barley.webp'),
    basil: require('@/assets/library/ingredient-categories/basil.webp'),
    beans: require('@/assets/library/ingredient-categories/beans.webp'),
    beef: require('@/assets/library/ingredient-categories/beef.webp'),
    beet_greens: require('@/assets/library/ingredient-categories/beet_greens.webp'),
    beets: require('@/assets/library/ingredient-categories/beets.webp'),
    biscuit: require('@/assets/library/ingredient-categories/biscuit.webp'),
    blackberries: require('@/assets/library/ingredient-categories/blackberries.webp'),
    blueberries: require('@/assets/library/ingredient-categories/blueberries.webp'),
    bratwurst: require('@/assets/library/ingredient-categories/bratwurst.webp'),
    bread: require('@/assets/library/ingredient-categories/bread.webp'),
    breadfruit: require('@/assets/library/ingredient-categories/breadfruit.webp'),
    broccoli: require('@/assets/library/ingredient-categories/broccoli.webp'),
    broccoli_raab: require('@/assets/library/ingredient-categories/broccoli_raab.webp'),
    brussels_sprouts: require('@/assets/library/ingredient-categories/brussels_sprouts.webp'),
    buckwheat_flour: require('@/assets/library/ingredient-categories/buckwheat_flour.webp'),
    buckwheat_groats: require('@/assets/library/ingredient-categories/buckwheat_groats.webp'),
    bulgur: require('@/assets/library/ingredient-categories/bulgur.webp'),
    burdock_root: require('@/assets/library/ingredient-categories/burdock_root.webp'),
    butter: require('@/assets/library/ingredient-categories/butter.webp'),
    cabbage: require('@/assets/library/ingredient-categories/cabbage.webp'),
    candies: require('@/assets/library/ingredient-categories/candies.webp'),
    carambola: require('@/assets/library/ingredient-categories/carambola.webp'),
    carrots: require('@/assets/library/ingredient-categories/carrots.webp'),
    cassava: require('@/assets/library/ingredient-categories/cassava.webp'),
    catsup: require('@/assets/library/ingredient-categories/catsup.webp'),
    cauliflower: require('@/assets/library/ingredient-categories/cauliflower.webp'),
    celery: require('@/assets/library/ingredient-categories/celery.webp'),
    cereals: require('@/assets/library/ingredient-categories/cereals.webp'),
    chard: require('@/assets/library/ingredient-categories/chard.webp'),
    chayote: require('@/assets/library/ingredient-categories/chayote.webp'),
    cheese: require('@/assets/library/ingredient-categories/cheese.webp'),
    cherries: require('@/assets/library/ingredient-categories/cherries.webp'),
    chicken: require('@/assets/library/ingredient-categories/chicken.webp'),
    chickpeas: require('@/assets/library/ingredient-categories/chickpeas.webp'),
    chives: require('@/assets/library/ingredient-categories/chives.webp'),
    cinnamon_buns: require('@/assets/library/ingredient-categories/cinnamon_buns.webp'),
    cocoa: require('@/assets/library/ingredient-categories/cocoa.webp'),
    collards: require('@/assets/library/ingredient-categories/collards.webp'),
    cookies: require('@/assets/library/ingredient-categories/cookies.webp'),
    coriander_leaves: require('@/assets/library/ingredient-categories/coriander_leaves.webp'),
    corn: require('@/assets/library/ingredient-categories/corn.webp'),
    corn_flour: require('@/assets/library/ingredient-categories/corn_flour.webp'),
    cornstarch: require('@/assets/library/ingredient-categories/cornstarch.webp'),
    couscous: require('@/assets/library/ingredient-categories/couscous.webp'),
    cowpeas: require('@/assets/library/ingredient-categories/cowpeas.webp'),
    crackers: require('@/assets/library/ingredient-categories/crackers.webp'),
    cranberries: require('@/assets/library/ingredient-categories/cranberries.webp'),
    cream: require('@/assets/library/ingredient-categories/cream.webp'),
    cress: require('@/assets/library/ingredient-categories/cress.webp'),
    croissants: require('@/assets/library/ingredient-categories/croissants.webp'),
    croutons: require('@/assets/library/ingredient-categories/croutons.webp'),
    crustaceans: require('@/assets/library/ingredient-categories/crustaceans.webp'),
    cucumber: require('@/assets/library/ingredient-categories/cucumber.webp'),
    currants: require('@/assets/library/ingredient-categories/currants.webp'),
    dates: require('@/assets/library/ingredient-categories/dates.webp'),
    doughnuts: require('@/assets/library/ingredient-categories/doughnuts.webp'),
    dove: require('@/assets/library/ingredient-categories/dove.webp'),
    duck: require('@/assets/library/ingredient-categories/duck.webp'),
    dulce_de_leche: require('@/assets/library/ingredient-categories/dulce_de_leche.webp'),
    edamame: require('@/assets/library/ingredient-categories/edamame.webp'),
    egg: require('@/assets/library/ingredient-categories/egg.webp'),
    eggnog: require('@/assets/library/ingredient-categories/eggnog.webp'),
    eggplant: require('@/assets/library/ingredient-categories/eggplant.webp'),
    escarole: require('@/assets/library/ingredient-categories/escarole.webp'),
    fat: require('@/assets/library/ingredient-categories/fat.webp'),
    fava_beans: require('@/assets/library/ingredient-categories/fava_beans.webp'),
    fennel: require('@/assets/library/ingredient-categories/fennel.webp'),
    figs: require('@/assets/library/ingredient-categories/figs.webp'),
    fish: require('@/assets/library/ingredient-categories/fish.webp'),
    frankfurter: require('@/assets/library/ingredient-categories/frankfurter.webp'),
    game_meat: require('@/assets/library/ingredient-categories/game_meat.webp'),
    garlic: require('@/assets/library/ingredient-categories/garlic.webp'),
    gelatins: require('@/assets/library/ingredient-categories/gelatins.webp'),
    ginger_root: require('@/assets/library/ingredient-categories/ginger_root.webp'),
    goose: require('@/assets/library/ingredient-categories/goose.webp'),
    grape_leaves: require('@/assets/library/ingredient-categories/grape_leaves.webp'),
    grapefruit: require('@/assets/library/ingredient-categories/grapefruit.webp'),
    grapes: require('@/assets/library/ingredient-categories/grapes.webp'),
    guavas: require('@/assets/library/ingredient-categories/guavas.webp'),
    ham: require('@/assets/library/ingredient-categories/ham.webp'),
    honey: require('@/assets/library/ingredient-categories/honey.webp'),
    horseradish: require('@/assets/library/ingredient-categories/horseradish.webp'),
    ice_cream: require('@/assets/library/ingredient-categories/ice_cream.webp'),
    ice_cream_cones: require('@/assets/library/ingredient-categories/ice_cream_cones.webp'),
    jams: require('@/assets/library/ingredient-categories/jams.webp'),
    jellies: require('@/assets/library/ingredient-categories/jellies.webp'),
    juice: require('@/assets/library/ingredient-categories/juice.webp'),
    kale: require('@/assets/library/ingredient-categories/kale.webp'),
    kefir: require('@/assets/library/ingredient-categories/kefir.webp'),
    kielbasa: require('@/assets/library/ingredient-categories/kielbasa.webp'),
    kiwifruit: require('@/assets/library/ingredient-categories/kiwifruit.webp'),
    knackwurst: require('@/assets/library/ingredient-categories/knackwurst.webp'),
    kohlrabi: require('@/assets/library/ingredient-categories/kohlrabi.webp'),
    kumquats: require('@/assets/library/ingredient-categories/kumquats.webp'),
    lamb: require('@/assets/library/ingredient-categories/lamb.webp'),
    lard: require('@/assets/library/ingredient-categories/lard.webp'),
    leavening_agents: require('@/assets/library/ingredient-categories/leavening_agents.webp'),
    leeks: require('@/assets/library/ingredient-categories/leeks.webp'),
    lemon_peel: require('@/assets/library/ingredient-categories/lemon_peel.webp'),
    lemons: require('@/assets/library/ingredient-categories/lemons.webp'),
    lentils: require('@/assets/library/ingredient-categories/lentils.webp'),
    lettuce: require('@/assets/library/ingredient-categories/lettuce.webp'),
    lima_beans: require('@/assets/library/ingredient-categories/lima_beans.webp'),
    limes: require('@/assets/library/ingredient-categories/limes.webp'),
    litchis: require('@/assets/library/ingredient-categories/litchis.webp'),
    mango: require('@/assets/library/ingredient-categories/mango.webp'),
    margarine: require('@/assets/library/ingredient-categories/margarine.webp'),
    marmalade: require('@/assets/library/ingredient-categories/marmalade.webp'),
    melons: require('@/assets/library/ingredient-categories/melons.webp'),
    milk: require('@/assets/library/ingredient-categories/milk.webp'),
    millet: require('@/assets/library/ingredient-categories/millet.webp'),
    miso: require('@/assets/library/ingredient-categories/miso.webp'),
    mollusks: require('@/assets/library/ingredient-categories/mollusks.webp'),
    mortadella: require('@/assets/library/ingredient-categories/mortadella.webp'),
    mushrooms: require('@/assets/library/ingredient-categories/mushrooms.webp'),
    mustard: require('@/assets/library/ingredient-categories/mustard.webp'),
    natto: require('@/assets/library/ingredient-categories/natto.webp'),
    nectarines: require('@/assets/library/ingredient-categories/nectarines.webp'),
    noodles: require('@/assets/library/ingredient-categories/noodles.webp'),
    nopales: require('@/assets/library/ingredient-categories/nopales.webp'),
    nuts: require('@/assets/library/ingredient-categories/nuts.webp'),
    oat_bran: require('@/assets/library/ingredient-categories/oat_bran.webp'),
    oil: require('@/assets/library/ingredient-categories/oil.webp'),
    okra: require('@/assets/library/ingredient-categories/okra.webp'),
    onion: require('@/assets/library/ingredient-categories/onion.webp'),
    oranges: require('@/assets/library/ingredient-categories/oranges.webp'),
    ostrich: require('@/assets/library/ingredient-categories/ostrich.webp'),
    pancakes: require('@/assets/library/ingredient-categories/pancakes.webp'),
    papayas: require('@/assets/library/ingredient-categories/papayas.webp'),
    parsley: require('@/assets/library/ingredient-categories/parsley.webp'),
    parsnips: require('@/assets/library/ingredient-categories/parsnips.webp'),
    "passion-fruit": require('@/assets/library/ingredient-categories/passion-fruit.webp'),
    pasta: require('@/assets/library/ingredient-categories/pasta.webp'),
    peaches: require('@/assets/library/ingredient-categories/peaches.webp'),
    peanut_butter: require('@/assets/library/ingredient-categories/peanut_butter.webp'),
    peanut_flour: require('@/assets/library/ingredient-categories/peanut_flour.webp'),
    peanuts: require('@/assets/library/ingredient-categories/peanuts.webp'),
    pears: require('@/assets/library/ingredient-categories/pears.webp'),
    peas: require('@/assets/library/ingredient-categories/peas.webp'),
    pepper: require('@/assets/library/ingredient-categories/pepper.webp'),
    pepperoni: require('@/assets/library/ingredient-categories/pepperoni.webp'),
    peppers: require('@/assets/library/ingredient-categories/peppers.webp'),
    persimmons: require('@/assets/library/ingredient-categories/persimmons.webp'),
    pheasant: require('@/assets/library/ingredient-categories/pheasant.webp'),
    phyllo_dough: require('@/assets/library/ingredient-categories/phyllo_dough.webp'),
    pickles: require('@/assets/library/ingredient-categories/pickles.webp'),
    pineapple: require('@/assets/library/ingredient-categories/pineapple.webp'),
    plantains: require('@/assets/library/ingredient-categories/plantains.webp'),
    plums: require('@/assets/library/ingredient-categories/plums.webp'),
    pomegranates: require('@/assets/library/ingredient-categories/pomegranates.webp'),
    pork: require('@/assets/library/ingredient-categories/pork.webp'),
    potato_flour: require('@/assets/library/ingredient-categories/potato_flour.webp'),
    potatoes: require('@/assets/library/ingredient-categories/potatoes.webp'),
    pumpkin: require('@/assets/library/ingredient-categories/pumpkin.webp'),
    quail: require('@/assets/library/ingredient-categories/quail.webp'),
    quinoa: require('@/assets/library/ingredient-categories/quinoa.webp'),
    radicchio: require('@/assets/library/ingredient-categories/radicchio.webp'),
    radishes: require('@/assets/library/ingredient-categories/radishes.webp'),
    raisins: require('@/assets/library/ingredient-categories/raisins.webp'),
    raspberries: require('@/assets/library/ingredient-categories/raspberries.webp'),
    ravioli: require('@/assets/library/ingredient-categories/ravioli.webp'),
    rhubarb: require('@/assets/library/ingredient-categories/rhubarb.webp'),
    rice: require('@/assets/library/ingredient-categories/rice.webp'),
    rice_flour: require('@/assets/library/ingredient-categories/rice_flour.webp'),
    rice_noodles: require('@/assets/library/ingredient-categories/rice_noodles.webp'),
    rutabagas: require('@/assets/library/ingredient-categories/rutabagas.webp'),
    rye_flour: require('@/assets/library/ingredient-categories/rye_flour.webp'),
    salad_dressing: require('@/assets/library/ingredient-categories/salad_dressing.webp'),
    salami: require('@/assets/library/ingredient-categories/salami.webp'),
    salsify: require('@/assets/library/ingredient-categories/salsify.webp'),
    salt: require('@/assets/library/ingredient-categories/salt.webp'),
    sauce: require('@/assets/library/ingredient-categories/sauce.webp'),
    sausage: require('@/assets/library/ingredient-categories/sausage.webp'),
    seaweed: require('@/assets/library/ingredient-categories/seaweed.webp'),
    seeds: require('@/assets/library/ingredient-categories/seeds.webp'),
    snacks: require('@/assets/library/ingredient-categories/snacks.webp'),
    sour_cream: require('@/assets/library/ingredient-categories/sour_cream.webp'),
    soy_flour: require('@/assets/library/ingredient-categories/soy_flour.webp'),
    soy_protein_isolate: require('@/assets/library/ingredient-categories/soy_protein_isolate.webp'),
    soy_sauce: require('@/assets/library/ingredient-categories/soy_sauce.webp'),
    soybeans: require('@/assets/library/ingredient-categories/soybeans.webp'),
    soymilk: require('@/assets/library/ingredient-categories/soymilk.webp'),
    spices: require('@/assets/library/ingredient-categories/spices.webp'),
    spinach: require('@/assets/library/ingredient-categories/spinach.webp'),
    squash: require('@/assets/library/ingredient-categories/squash.webp'),
    strawberries: require('@/assets/library/ingredient-categories/strawberries.webp'),
    sugar: require('@/assets/library/ingredient-categories/sugar.webp'),
    sweet_potato: require('@/assets/library/ingredient-categories/sweet_potato.webp'),
    sweetener: require('@/assets/library/ingredient-categories/sweetener.webp'),
    syrup: require('@/assets/library/ingredient-categories/syrup.webp'),
    taco_shells: require('@/assets/library/ingredient-categories/taco_shells.webp'),
    tamarinds: require('@/assets/library/ingredient-categories/tamarinds.webp'),
    tangerines: require('@/assets/library/ingredient-categories/tangerines.webp'),
    tapioca: require('@/assets/library/ingredient-categories/tapioca.webp'),
    taro: require('@/assets/library/ingredient-categories/taro.webp'),
    tofu: require('@/assets/library/ingredient-categories/tofu.webp'),
    tomatillos: require('@/assets/library/ingredient-categories/tomatillos.webp'),
    tomatoes: require('@/assets/library/ingredient-categories/tomatoes.webp'),
    tortellini: require('@/assets/library/ingredient-categories/tortellini.webp'),
    tortillas: require('@/assets/library/ingredient-categories/tortillas.webp'),
    turkey: require('@/assets/library/ingredient-categories/turkey.webp'),
    turnips: require('@/assets/library/ingredient-categories/turnips.webp'),
    vanilla_extract: require('@/assets/library/ingredient-categories/vanilla_extract.webp'),
    veal: require('@/assets/library/ingredient-categories/veal.webp'),
    vermicelli: require('@/assets/library/ingredient-categories/vermicelli.webp'),
    vinegar: require('@/assets/library/ingredient-categories/vinegar.webp'),
    waffles: require('@/assets/library/ingredient-categories/waffles.webp'),
    wasabi: require('@/assets/library/ingredient-categories/wasabi.webp'),
    waterchestnuts: require('@/assets/library/ingredient-categories/waterchestnuts.webp'),
    watercress: require('@/assets/library/ingredient-categories/watercress.webp'),
    waxgourd: require('@/assets/library/ingredient-categories/waxgourd.webp'),
    wheat_bran: require('@/assets/library/ingredient-categories/wheat_bran.webp'),
    wheat_flour: require('@/assets/library/ingredient-categories/wheat_flour.webp'),
    whey: require('@/assets/library/ingredient-categories/whey.webp'),
    wild_rice: require('@/assets/library/ingredient-categories/wild_rice.webp'),
    yam: require('@/assets/library/ingredient-categories/yam.webp'),
    yambean: require('@/assets/library/ingredient-categories/yambean.webp'),
    yeast_extract_spread: require('@/assets/library/ingredient-categories/yeast_extract_spread.webp'),
    yogurt: require('@/assets/library/ingredient-categories/yogurt.webp'),
}


export default {
    avocado,
    blender,
    bread,
    butter,
    caffeine,
    cheese,
    corn,
    eggplant,
    eggs,
    fish,
    fructose,
    gluten,
    meat,
    melon,
    milk,
    oil,
    onion,
    parsley,
    pasta,
    peppers,
    recipe,
    sucrose,
    vegetarian,

    icons,
}