export default interface INutritional {
    calories?: number,
    ndbNumber?: number,
    alphaCaroteneUg?: number,
    betaCaroteneUg?: number,
    betaCryptoxanthinUg?: number,
    carbG?: number,
    cholesterolMg?: number,
    cholineMg?: number,
    fiberG?: number,
    luteinZeaxanthinUg?: number,
    lycopeneUg?: number,
    niacinMg?: number,
    proteinG?: number,
    retinolUg?: number,
    riboflavinMg?: number,
    seleniumUg?: number,
    sugarTotalG?: number,
    thiaminMg?: number,
    waterG?: number,
    fatMonoG?: number,
    fatPolyG?: number,
    fatSaturatedG?: number,
    fatTotalG?: number,
    mineralCalciumMg?: number,
    mineralCopperMg?: number,
    mineralIronMg?: number,
    mineralMagnesiumMg?: number,
    mineralPhosphorusMg?: number,
    mineralPotassiumMg?: number,
    mineralSodiumMg?: number,
    mineralZincMg?: number,
    vitARaeUg?: number,
    vitB12Ug?: number,
    vitB6Mg?: number,
    vitCMg?: number,
    vitEMg?: number,
    vitKUg?: number,
}

interface nutrientMapItem {
    title: string,
    unit: string
}

export const nutrientMap: Record<keyof INutritional, nutrientMapItem> = {
    calories: {title: 'Calories', unit: 'kcal'},
    ndbNumber: {title: 'Nutrient Data Bank Number', unit: ''},
    alphaCaroteneUg: {title: 'Alpha Carotene', unit: 'μg'},
    betaCaroteneUg: {title: 'Beta Carotene', unit: 'μg'},
    betaCryptoxanthinUg: {title: 'Beta Cryptoxanthin', unit: 'μg'},
    carbG: {title: 'Carbohydrates', unit: 'g'},
    cholesterolMg: {title: 'Cholesterol', unit: 'mg'},
    cholineMg: {title: 'Choline', unit: 'mg'},
    fiberG: {title: 'Fiber', unit: 'g'},
    luteinZeaxanthinUg: {title: 'Lutein + Zeaxanthin', unit: 'μg'},
    lycopeneUg: {title: 'Lycopene', unit: 'μg'},
    niacinMg: {title: 'Niacin', unit: 'mg'},
    proteinG: {title: 'Protein', unit: 'g'},
    retinolUg: {title: 'Retinol', unit: 'μg'},
    riboflavinMg: {title: 'Riboflavin', unit: 'mg'},
    seleniumUg: {title: 'Selenium', unit: 'μg'},
    sugarTotalG: {title: 'Sugar', unit: 'g'},
    thiaminMg: {title: 'Thiamin', unit: 'mg'},
    waterG: {title: 'Water', unit: 'g'},
    fatMonoG: {title: 'Monounsaturated fatty acids', unit: 'g'},
    fatPolyG: {title: 'Polyunsaturated fatty acids', unit: 'g'},
    fatSaturatedG: {title: 'Saturated fatty acids', unit: 'g'},
    fatTotalG: {title: 'Total fatty acids', unit: 'g'},
    mineralCalciumMg: {title: 'Calcium', unit: 'mg'},
    mineralCopperMg: {title: 'Copper', unit: 'mg'},
    mineralIronMg: {title: 'Iron', unit: 'mg'},
    mineralMagnesiumMg: {title: 'Magnesium', unit: 'mg'},
    mineralPhosphorusMg: {title: 'Phosphorus', unit: 'mg'},
    mineralPotassiumMg: {title: 'Potassium', unit: 'mg'},
    mineralSodiumMg: {title: 'Sodium', unit: 'mg'},
    mineralZincMg: {title: 'Zinc', unit: 'mg'},
    vitARaeUg: {title: 'Vitamin A - RAE', unit: 'μg'},
    vitB12Ug: {title: 'Vitamin B12', unit: 'μg'},
    vitB6Mg: {title: 'Vitamin B6', unit: 'mg'},
    vitCMg: {title: 'Vitamin C', unit: 'mg'},
    vitEMg: {title: 'Vitamin E', unit: 'mg'},
    vitKUg: {title: 'Vitamin K', unit: 'μg'},
}